MAINTAINERS.md
Makefile
README.md

- added travix-ui-kit badges
- added scripts for generating and pushing changelog
- updated accordingly to the changes in the Makefile

updated readme.md makefile and maintainers.md

---

components/_helpers.js
components/index.scss
components/price/price.js
components/price/price.md
components/price/price.scss
tests/unit/helpers/helpers.spec.js
tests/unit/price/__snapshots__/price.spec.js.snap
tests/unit/price/price.spec.js
themes/_default.yaml

Adds the Price component to Travix UI Kit.
Fixes #11.
- Diffs
- Look at the styleguide
Adds Unit tests for Price component, reaching 100% coverage

Price component

---

components/index.js
components/index.scss
components/list/list.js
components/list/list.md
components/list/list.scss
tests/unit/list/__snapshots__/list.spec.js.snap
tests/unit/list/list.spec.js
themes/_default.yaml

Added List component (later on will be extended with possibility to have icon)

Added List component

---

README.md

- Fixes typo on `README.md`
- Diffs

Fixes typo on README.md

---

builder/generateThemeFile.js
builder/getStylesAndSaveTheme.js
package.json
tests/unit/builder/generateThemeFile.spec.js

Extend default theme by custom theme

---

components/calendar/calendar.md

* Fixes the Calendar's doc issue.
- `components/calendar.md`

Fixes the calendar's doc example

---

components/collapse/collapse.js
components/collapse/collapse.md
components/collapse/collapseItem.js
components/collapse/collapseItem.scss
tests/unit/collapse/__snapshots__/collapse.render.spec.js.snap
tests/unit/collapse/__snapshots__/collapseItem.render.spec.js.snap
tests/unit/collapse/collapse.handleItemClick.spec.js
tests/unit/collapse/collapse.render.spec.js
themes/_default.yaml

- added new property for collapse component (`defaultActiveKey`) 
- updated theme
- changed styles for collapse component

Improvements for Collapse component

---

.eslintrc
components/button/button.js
components/price/price.js

- add rule "prefer stateless components"
- add rule "ternary always requires a new line"
- fixes for these rules

ESlint improvements

---

builder/webpack.config.js
components/collapse/collapse.scss
components/index.scss
components/modal/modal.js
components/modal/modal.scss
components/price/price.js
themes/_default.yaml

* changed styles for Modal component
* updated theme
* changed settings for `autoprefixer`

Improvements for Modal component

---

styleguide.config.js

Fix for #64 
Made as proposed [here](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#webpackconfig)

Update styleguide.config.js to work with latest minor version of react-styleguidist

---

components/modal/modal.js
tests/unit/modal/__snapshots__/modal.render.spec.js.snap
tests/unit/modal/modal.render.spec.js

Add posibility to pass mods through `props` in modal component

---

components/list/list.scss

Added variables to the List component classes

Added variables to the List classes

---

.travis.yml
builder/builder.js
components/autoComplete/autoComplete.scss
components/autoComplete/autoCompleteItem.scss
components/button/button.scss
components/calendar/calendar.scss
components/checkbox/checkbox.scss
components/collapse/collapse.scss
components/collapse/collapseItem.scss
components/dropDown/dropDown.scss
components/input/input.scss
components/list/list.scss
components/modal/modal.scss
components/price/price.scss
components/radioButton/radioButton.scss
components/spinner/spinner.scss
package.json
styleguide.html
tests/unit/builder/builder.spec.js
themes/_default.yaml

* Changes the `builder` to use the new processor `cssvars` to generate the `dist/theme.css` with a general declaration of all variables.
* Changes the `components/**/*.scss` files to use CSS variables instead of SCSS variables.
* Changes the `styleguide.html` to include the `theme.css` at the `<head>`.
- Diffs
- Check your component's styles
- Check the styleguide
One test fixed, all tests are passing.

Convert SCSS Variables into CSS Custom Properties/Variables

---

components/button/button.js
components/button/button.md
components/button/button.scss
tests/unit/button/button.spec.js
themes/_default.yaml

Adds the ghost button variation to UI-KIT
This PR solves the _ghost_ rendering issue on #73

adds ghost button

---

components/index.scss
components/rating/rating.js
components/rating/rating.md
components/rating/rating.scss
tests/unit/rating/__snapshots__/rating.spec.js.snap
tests/unit/rating/rating.spec.js

- Adds the SlidingPanel component
- Adds the SlidingPanel SCSS file
- Adds the SlidingPanel Markdown file
- Adds the SlidingPanel unit tests
Closes #113 
- Diffs
- Should be making 100% coverage.

Adds the rating component

---

components/index.js
components/index.scss
components/slidingPanel/slidingPanel.js
components/slidingPanel/slidingPanel.md
components/slidingPanel/slidingPanel.scss
tests/unit/slidingPanel/__snapshots__/slidingPanel.spec.js.snap
tests/unit/slidingPanel/slidingPanel.spec.js
themes/_default.yaml

* Adds the `SlidingPanel` component
* Adds the `SlidingPanel` SCSS file
* Adds the `SlidingPanel` Markdown file
* Adds the `SlidingPanel` unit tests
Note: Closes issue #110 
- Diffs
Should be making 100% coverage.

Adds the SlidingPanel component

---

components/index.js

HOT-FIX for export rating component

HOT-FIX for export rating component

---

components/modal/modal.js
tests/unit/modal/__snapshots__/modal.handleOverlayClick.spec.js.snap
tests/unit/modal/__snapshots__/modal.render.spec.js.snap
tests/unit/modal/modal.close.spec.js
tests/unit/modal/modal.open.spec.js
tests/unit/modal/modal.render.spec.js

- Fix for #109 
- Diffs
- Should be making 100% coverage.

#109 modal bug

---

components/radioButton/radioButton.scss

We are using wrong color for radio button, should be `tx-generic-color-secondary-darker`. This PR solves this small issue

Fixed color for radio button

---

components/calendar/calendar.js
components/calendar/views/days.js
components/datePicker/datePicker.js
components/datePicker/datePicker.md
components/datePicker/datePicker.scss
components/index.js
components/index.scss
tests/unit/calendar/calendar.handleItemMouseDown.spec.js
tests/unit/calendar/calendar.normal.spec.js
tests/unit/calendar/calendar.range.spec.js
tests/unit/datePicker/__snapshots__/datePicker.render.spec.js.snap
tests/unit/datePicker/datePicker.blurInput.spec.js
tests/unit/datePicker/datePicker.focusInput.spec.js
tests/unit/datePicker/datePicker.handleChange.spec.js
tests/unit/datePicker/datePicker.handleInputBlur.spec.js
tests/unit/datePicker/datePicker.handleInputFocus.spec.js
tests/unit/datePicker/datePicker.handleItemMouseDown.spec.js
tests/unit/datePicker/datePicker.initInputRef.spec.js
tests/unit/datePicker/datePicker.render.spec.js
themes/_default.yaml

* Adds the `DatePicker` component
* Adds the `DatePicker` SCSS file
* Adds the `DatePicker` Markdown file
* Adds the `DatePicker` unit tests
- Diffs
Should be making 100% coverage.

Adds the DatePicker component

---

styleguide.html

* Fixes a typo on the UserAgent detection removing the unnecessary 2nd parameter passed to the `parseFloat`
- Diffs

Fixes typo on the UserAgent detection

---

components/datePicker/datePicker.md

Fix datepicker demo

---

components/collapse/collapse.js
components/collapse/collapse.md
components/collapse/collapseItem.js
components/collapse/collapseItem.scss
tests/unit/collapse/__snapshots__/collapse.render.spec.js.snap
tests/unit/collapse/__snapshots__/collapseItem.render.spec.js.snap
tests/unit/collapse/collapse.render.spec.js
tests/unit/collapse/collapseItem.render.spec.js

This PR provides the possibility to customize the position of the icon which is displayed on every collapse item (either left or right, left by default).

Collapse component adjustments

---

components/badge/badge.js
components/badge/badge.md
components/badge/badge.scss
tests/unit/badge/__snapshots__/badge.spec.js.snap
tests/unit/badge/badge.spec.js
themes/_default.yaml

* added new `prop`
* fixed bug
* updated documentation

Improvements for Badge component

---

components/autoComplete/autoComplete.js
components/slidingPanel/slidingPanel.js
styleguide.html

* Improves the polyfill loader to use feature detection rather than UA Sniffing
- Diffs.

Improves the polyfill loader to use feature detection

---

components/badge/badge.js
components/badge/badge.md
components/badge/badge.scss
components/price/price.js
tests/unit/badge/__snapshots__/badge.spec.js.snap
tests/unit/badge/badge.spec.js
tests/unit/price/__snapshots__/price.spec.js.snap

Improvements for price and badge
Fix issue #132
**Price with discount:**
before:
after:
**badge:**
before:
after:
Diffs

Improvements for price and badge

---

README.md

Fix path to bundle css file in readme

---

components/button/button.md
components/button/button.scss
themes/_default.yaml

- Adds link variation to button
- Diffs

Adds link variation to button

---

components/googleMap/googleMap.js
components/slidingPanel/slidingPanel.scss
themes/_default.yaml

* Adds the possibility to scroll on the content of the SlidePanel component.
* Adds an `eslint-disable-line` on the `console.warn` in the Google Maps component.
This fixes the issue #141 
* Diffs

Makes the SlidePanel scrollable

---

components/autoComplete/autoComplete.js
components/autoComplete/autoCompleteItem.js
components/badge/badge.js
components/button/button.js
components/calendar/calendar.js
components/calendar/views/days.js
components/carousel/carousel.js
components/carousel/carouselItem.js
components/carousel/carouselMarkers.js
components/carousel/carouselPage.js
components/carousel/carouselTrack.js
components/checkbox/checkbox.js
components/collapse/collapse.js
components/collapse/collapseItem.js
components/dropDown/dropDown.js
components/dropDown/dropdownFilterOptionComponent.js
components/global/global.js
components/googleMap/googleMap.js
components/input/input.js
components/list/list.js
components/messageBox/messageBox.js
components/modal/modal.js
components/price/price.js
components/radioButton/radioButton.js
components/rating/rating.js
components/slidingPanel/slidingPanel.js
components/slidingPanel/slidingPanelHeader.js
components/spinner/spinner.js

* Changes the components to use the `prop-types` package.
This fixes the issue #135.
* Diffs

Changes the components to use the 'prop-types' package

---

components/dropDown/dropDown.js
components/dropDown/dropDown.md
components/dropDown/dropDown.scss
components/input/input.js
components/input/input.md
components/input/input.scss
tests/unit/dropDown/__snapshots__/dropDown.render.spec.js.snap
tests/unit/dropDown/dropDown.render.spec.js
tests/unit/input/__snapshots__/input.render.spec.js.snap
tests/unit/input/input.render.spec.js
themes/_default.yaml

* added states for dropDown component
* added states for input component
Diff
fixed / added

Input and dropdown improvements

---

components/dropDown/dropDown.scss

**WHAT DOES THIS PR DO:**
updated styles for dropdown control (including disabled state)
**WHERE SHOULD THE REVIEWER START:**
diff
**UNIT AND/OR FUNCTIONAL TESTS:**
none
**SCREENSHOT:**

Dropdown control updates

---

components/collapse/collapseItem.js
package.json
tests/unit/collapse/__snapshots__/collapseItem.render.spec.js.snap

chore(package): update jest-cli to version 21.0.1

---

tests/unit/overlayTrigger/overlayTrigger.hideElement.spec.js
tests/unit/overlayTrigger/overlayTrigger.showElement.spec.js

* Improves the overlayTrigger's unit tests to be back to 100% coverage
- Diffs

Improves the overlayTrigger's unit tests to be back to 100% coverage

---

PULL_REQUEST_TEMPLATE.md

* Adds the `PULL_REQUEST_TEMPLATE.md` to provide some contributing guidelines.
* Diffs

Adds the PULL_REQUEST_TEMPLATE.md

---

ISSUE_TEMPLATE.md

* Adds the `ISSUE_TEMPLATE.md` to improve our contributing guidelines.
- DIffs

Adds the ISSUE_TEMPLATE.md to improve our contributing guidelines

---

CONTRIBUTING.md

* Adds the CONTRIBUTING.md to improve our community and contributing guidelines
- Diffs

Adds the CONTRIBUTING.md to improve our community and contributing guidelines

---

package.json

* Updates `jest-cli` to version 21.1.0.
* Updates `jest` to version 21.1.0.
Closes #182 
Closes #183 
* Diffs

chore(package): update jest and jest-cli to version 21.1.0

---

components/slidingPanel/slidingPanel.js
components/slidingPanel/slidingPanel.md
components/slidingPanel/slidingPanelHeader.js
components/slidingPanel/slidingPanelHeader.scss
tests/unit/slidingPanel/__snapshots__/slidingPanel.spec.js.snap
tests/unit/slidingPanel/__snapshots__/slidingPanelHeader.spec.js.snap
tests/unit/slidingPanel/slidingPanel.spec.js
tests/unit/slidingPanel/slidingPanelHeader.spec.js

* adds props to be able to call passed function before closing starts and prevent closing if it returns false;
* adds props for customizing left / right blocks in the header (custom buttons, etc.);
components/slidingPanel/slidingPanel.js

Sliding panel improvements

---

components/slidingPanel/slidingPanel.js

Fixes the error with NodeList on IE11
Diffs

fixes NodeList to Array

---

components/slidingPanel/slidingPanel.md

Fixes the demo for the sidepanel: makes it possible to close the one with preclosing hook
see the diff

Fixes the demo for the sidepanel

---

components/toggleButton/toggleButton.js
components/toggleButton/toggleButton.md

* Changes the ToggleButton component to accept classNames. This is particularly useful for CSS Modules
- Diffs
- Styleguide

Changes the ToggleButton component to accept classNames

---

components/button/button.js
components/button/button.md
tests/unit/button/__snapshots__/button.spec.js.snap

Add ability for extending to the button
diff
tests fixing in progress

Add ability for extending to the button

---

themes/_default.yaml

Fixed issue with button colors

---

components/button/button.js
themes/_default.yaml

Fix yaml property and props validation
Diff

Fix yaml property and props validation

---

components/list/list.js
tests/unit/list/__snapshots__/list.spec.js.snap
tests/unit/list/list.spec.js

Added prop `renderEmptyItems` to the `List` component. Value by default is `true`.
Diff

Add prop renderEmptyItems to the List component

---

components/dropDown/dropDown.js
components/dropDown/dropDown.md
components/dropDown/dropDown.scss
tests/unit/dropDown/__snapshots__/dropDown.render.spec.js.snap
tests/unit/dropDown/dropDown.render.spec.js
tests/unit/dropDown/dropDown.valueRenderer.spec.js

* Changes the `DropDown` component to support the `icon` attribute that affects the display of value label. 
* Diffs

Add icon prop to dropdown

---

components/price/price.js
components/price/price.md
tests/unit/price/__snapshots__/price.spec.js.snap
tests/unit/price/price.spec.js

> Added `unstyled` prop into `Price` component to have a possibility to render price inline without any styling.
> Review changes and check them on our new awesome acceptance! 😄

Add unstyled prop to Price component

---

components/button/button.md
components/button/button.scss

This PR fixes wrong styling for ghost and link buttons in disabled state and adds ability to check disabled state for all types of buttons
Check diff

Fix styles for ghost and link buttons

---

package.json
styleguide.config.js
styleguide.html

* added `babel-polyfill` - it fixes issue in IE
* diff

added polyfill for Array.prototype.includes

---

components/autoComplete/autoComplete.js
components/slidingPanel/slidingPanel.md
tests/unit/autoComplete/__snapshots__/autoComplete.render.spec.js.snap
tests/unit/autoComplete/autoComplete.applyActiveKey.spec.js

* fixed autocomplete behavior
* small refactoring
* diff
* added
1. go to https://travix-international.github.io/travix-ui-kit/#autocomplete
2. click inside autocomplete input
3. type `a`
4. click outside autocomplete input
5. value in input should be `Apple 1` (**it works**)
6. perform `2`, `3` and `4` again
7. value in input should be `Apple 1` (**it does not work**)

fix for autocomplete behavior

---

components/price/price.js

Added className to price component
diffs

Fixed price component

---

tests/unit/calendar/calendar.normal.spec.js
tests/unit/calendar/calendar.range.spec.js

* mock `Date` for some unit tests
* diff

fixed tests for calendar

---

components/toggleButton/toggleButton.js

Add dataAttrs prop
diff
Does it makes sense to add dataAttrs to root element? Because it might be more interesting to know on which exact item user clicked.

Toggle button component add dataAttrs

---

components/list/list.js

List component fixes

---

components/googleMap/googleMap.css
components/googleMap/googleMap.js
tests/unit/googleMap/__snapshots__/googleMap.render.spec.js.snap
tests/unit/googleMap/googleMap.render.spec.js

- fix styling issue with custom marker
- add className and dataAttr properties

fix styling issue with custom marker; add className and dataAttr properties

---

components/messageBox/messageBox.js
tests/unit/messageBox/__snapshots__/messageBox.spec.js.snap
tests/unit/messageBox/messageBox.spec.js
themes/_default.yaml

- Add className prop
- Fix success color css-var
diff

Fix theme for messagebox

---

components/tabs/tab.css
components/tabs/tab.js
components/tabs/tabs.js
tests/unit/helpers/helpers.spec.js
tests/unit/tabs/__snapshots__/tabs.spec.js.snap

* Removed usage of other props from Tab/Tabs component
diff

Remove otherProps from Tab/Tabs components

---

components/input/input.js
components/input/input.scss
tests/unit/input/__snapshots__/input.render.spec.js.snap

Fixed input component
Diffs
Decision to leave border the same color on hover for disabled input and give disabled input 0.5 opacity was made by Nicolas.

Fixed input component

---

components/checkbox/checkbox.js
components/radioButton/radioButton.js
tests/unit/checkbox/__snapshots__/checkbox.spec.js.snap
tests/unit/checkbox/checkbox.spec.js
tests/unit/radioButton/__snapshots__/radioButton.spec.js.snap
tests/unit/radioButton/radioButton.spec.js

-     add className property Checkbox and RadioButton components

Add className property Checkbox and RadioButton components

---

components/dropDown/dropDown.js
tests/unit/dropDown/__snapshots__/dropDown.render.spec.js.snap
tests/unit/dropDown/dropDown.render.spec.js

Add `className` and 'disabled` props
diff

Add missed props for Dropdown component

---

components/index.js
components/index.scss
components/loadingOverlay/loadingOverlay.css
components/loadingOverlay/loadingOverlay.js
components/loadingOverlay/loadingOverlay.md
components/spinner/spinner.js
tests/unit/loadingOverlay/__snapshots__/loadingOverlay.spec.js.snap
tests/unit/loadingOverlay/loadingOverlay.spec.js

Implements loading overlay component for better loading experience. 
It uses Spinner component inside.
components/loadingOverlay/loadingOverlay.js

Implement loading overlay component

---

package.json

Update now package version for fixing errors

Updates "now version

---

.gitignore
package-lock.json

Restore `package-lock.json` from gitignore

Restore `package-lock.json` from gitignore

---

components/global/global.js
components/modal/modal.js
components/modal/modal.md
tests/unit/global/global.handleClick.spec.js
tests/unit/modal/__snapshots__/modal.render.spec.js.snap
tests/unit/modal/modal.componentWillReceiveProps.spec.js
tests/unit/slidingPanel/__snapshots__/slidingPanel.spec.js.snap

Fix event propagation for global and fix double closing for modal.
Diff

Fix event propagation for global and fix double closing for modal

---

CHANGELOG.md
Makefile
README.md
components/badge/badge.js
components/badge/badge.md
components/badge/badge.scss
package-lock.json
package.json
tests/unit/badge/__snapshots__/badge.spec.js.snap
tests/unit/badge/badge.spec.js

* Closes #329 
* Introduced new prop `align` into `<Badge />` component. It accepts one of these 3 values: [`start`, `center`, `end`]. The default behavior is not changed and this new prop is optional.
* Markdown of the `<Badge />` component is refactored to be more user-friendly and nice. 😄 
* Made badge is more responsive: now left and right badges have limitation by width and will not exceed 100% of the container width. Also, arrows were improved and became really responsive (this approach already used in `Hotels` widget and the solution is stolen from there. 😄 This is how it looks now if we have a multiline badge:
* Check the diffs and test an acceptance link.
* Added

Extend Badge component

---

components/modal/modal.js
tests/unit/modal/__snapshots__/modal.handleOverlayClick.spec.js.snap
tests/unit/modal/__snapshots__/modal.render.spec.js.snap

Disable body scroll when modal is opened
Fix #331

Fix body scroll when modal is open

---

components/modal/modal.md

Remove wrong persist on markdown file

---

components/modal/modal.js
tests/unit/modal/__snapshots__/modal.render.spec.js.snap
tests/unit/modal/modal.render.spec.js

Add suport to data attributes to the modal component. Work done by @sleepwalky.
Diffs. No visual changes applied.

add data attrs to modal / update tests and snaps
