package.json, webpack.config.js
* updates packages versions (greenkeeper updates)
* removes node_modules from scss loader in webpack because of build problems when loading the package as a npm module.
* differences
=> removed node_modules from webpack scss loader

components/_helpers.js, components/button/button.scss, components/spinner/spinner.scss, tests/unit/button/__snapshots__/button.spec.js.snap, tests/unit/helpers/helpers.spec.js, tests/unit/spinner/__snapshots__/spinner.spec.js.snap
Updated according to the new BEM standards (see [here](https://en.bem.info/methodology/quick-start/#modifier))
Modified:
- mods helper.js 
- modifiers class names
- unit tests
Modifiers were changed from `block-name--modifier` to `block-name_modifier`
=> Updated mods helper and class names according to the new BEM standards

builder/generateThemeFile.js, builder/getStylesAndSaveTheme.js, tests/unit/builder/generateThemeFile.spec.js, tests/unit/builder/getStylesAndSaveTheme.spec.js
* Changes the `getStylesAndSaveTheme.js` to use the `fs.watchFile` instead of the `fs.watch`. This solves a problem of getting the `change` event being triggered more than once.
* Changes the `getStylesAndSaveTheme.js` to log a message whenever it detects changes and is able to rebuild the `theme.scss`.
* Changes the `getStylesAndSaveTheme.js` to log the error on the shell when an error happens on the watch callback.
* Changes the `generateThemeFile.js` to wrap the `themeBuilder` call in a `try..catch` rejecting the promise on error.
- Diffs
=> Improvement of the builder watcher

components/price/price.js
Removes the _xs_ value from the `size`'s `propTypes` definition.
- Diffs
=> Fixes size's prop definition

README.md, builder/builder.js, builder/index.js, builder/webpack.config.js, components/button/button.js, components/spinner/spinner.js, tests/unit/builder/builder.spec.js, tests/unit/builder/index.spec.js, tests/unit/button/__snapshots__/button.spec.js.snap, tests/unit/button/button.spec.js, tests/unit/helpers/helpers.spec.js
* Increases the coverage by removing certain conditionals that verified if a property is set when it they have a default value.
* Changes the `builder.js` to return the `Promise` instead of executing it.
* Adds the `bail` property to the `webpack.config.js` to force it to fail immediately so that we get the exact error instead of the last one.
- Diffs
All tests are passing.
=> Fixes issue #31 - Changes the builder to properly catch rejections and to output the errors on the webpack process

components/price/price.js, package.json, tests/unit/price/__snapshots__/price.spec.js.snap, tests/unit/price/price.spec.js
When an integer number is provided to the Price component, the `ensureDecimalPrecision` function does not handle the _undefined_ (attempts to convert it to string).
This PR changes the `ensureDecimalPrecision` to have a default value on the `value` attribute to be empty string, fixing the issue.
- Diffs, specially the file `price.js`.
Tests covering the issue added.
=> fix for price component

components/calendar/calendar.js, tests/unit/calendar/calendar.normal.spec.js, tests/unit/calendar/calendar.range.spec.js
- Resets `renderDate` to `maxLimit`'s month when `renderDate` is bigger than `maxLimit`.
- Removes dependencies related to current date on `Calendar`'s unit tests
- Diffs
Fixes calendar's tests.
=> Removes dependencies related to current date on Calendar's unit tests

.gitignore, Makefile, README.md
* adds possibility to publish travix-ui-kit on GitHub Pages
* scripts are added to the `Makefile`, so with every release on npm via Makefile we are releasing new version to the documentation page
=> added scripts to Makefile for publishing travix-ui-kit to github pages

components/autoComplete/autoComplete.js, components/autoComplete/autoCompleteItem.js, components/button/button.js, components/calendar/calendar.js, components/checkbox/checkbox.js, components/input/input.js, components/list/list.js, components/modal/modal.js, components/price/price.js, components/radioButton/radioButton.js, components/spinner/spinner.js, tests/unit/autoComplete/__snapshots__/autoComplete.render.spec.js.snap, tests/unit/autoComplete/autoComplete.render.spec.js, tests/unit/autoCompleteItem/__snapshots__/autoCompleteItem.render.spec.js.snap, tests/unit/autoCompleteItem/autoCompleteItem.render.spec.js, tests/unit/button/__snapshots__/button.spec.js.snap, tests/unit/button/button.spec.js, tests/unit/calendar/__snapshots__/calendar.normal.spec.js.snap, tests/unit/calendar/calendar.normal.spec.js, tests/unit/checkbox/__snapshots__/checkbox.spec.js.snap, tests/unit/checkbox/checkbox.spec.js, tests/unit/input/__snapshots__/input.render.spec.js.snap, tests/unit/input/input.render.spec.js, tests/unit/list/__snapshots__/list.spec.js.snap, tests/unit/list/list.spec.js, tests/unit/radioButton/__snapshots__/radioButton.spec.js.snap, tests/unit/radioButton/radioButton.spec.js, tests/unit/spinner/__snapshots__/spinner.spec.js.snap, tests/unit/spinner/spinner.spec.js
- Button component `restProps` for data attributes for simple button fix
- Don't mutate props.mods (fix for #77 ): slice mods if provided or just use a new array
- Diff
- 100% covereage
- added new snapshots
- updated old ones
=> Button restProps and non-mutating mods

package.json, styleguide.config.js
* Fixes the `styleguide.config.js` to work with Webpack 2.
* Locks the version of `react-styleguidist` to v5.1.10, since >= v5.2.0 have issues with our JSDoc ( check https://github.com/styleguidist/react-styleguidist/releases/tag/v5.2.0 ).
* Diffs
* Build the style guide.
=> Fixes the config for Webpack 2 on the styleguide.config.js

components/collapse/collapseItem.js, tests/unit/collapse/__snapshots__/collapse.render.spec.js.snap
* added othe props for collapseItem component
* temporary adds the package dependency for `create-react-class`
=> Improvements for CollapseItem component

README.md, package.json
* Moves all dependencies to devDependencies since the UI Kit became a product of a release
This fixes issue #98 
- Diffs
=> Move dependencies to devDependencies

components/modal/modal.js, tests/unit/button/__snapshots__/button.spec.js.snap, tests/unit/button/button.spec.js, tests/unit/modal/modal.close.spec.js, tests/unit/modal/modal.componentDidMount.spec.js, tests/unit/modal/modal.componentWillUnmount.spec.js, tests/unit/modal/modal.open.spec.js
The current implementation of the Modal component doesn't allow it to be open by default (it only opens after a prop change). This PR allows a `<Modal active />` to display as expected.
I've also included some small miscellaneous fixes, let me know if there's no problem merging with this one:
- Switched references from `window.document.requestAnimationFrame` (no such property exists on `document`) to `window.requestAnimationFrame`.
- Updated the Button spec file to always pass required props (removes the big bold red warnings when running tests)
Fixes #103
=> Allow Modal window to be active by default

components/dropDown/dropDown.scss, themes/_default.yaml
* Fixes an issue with HEX values being passed to `rgba()` via CSS Custom Variables.
* Reverts the deletion of the `react-select` variables that define the styles of those components (Dropdown).
* Changes the dropDown.scss approach (on certain colors' variables) to override instead of setting them, since we need them to be dynamic (via CSS Variables).
* Converted all non-generic colors (that were using the `*colorName` approach) to be CSS Variables, in the `_default.yaml`.
- Diffs
All tests should be passing.
=> Adds removed variables for react select and fixes RGB values under CSS Variables

components/index.js, components/slidingPanel/slidingPanel.js, tests/unit/slidingPanel/slidingPanel.spec.js
* Adds usage of refs to remove usage of `findDOMNode`.
- Diffs
Adds `renderTree.unmount()` to pass via `componentWillUnmount()`.
=> Change SlidingPanel to use the refs

components/index.scss, components/slidingPanel/slidingPanel.js, components/slidingPanel/slidingPanel.md, components/slidingPanel/slidingPanel.scss, components/slidingPanel/slidingPanelHeader.js, components/slidingPanel/slidingPanelHeader.scss, package.json, tests/unit/slidingPanel/__snapshots__/slidingPanel.spec.js.snap, tests/unit/slidingPanel/__snapshots__/slidingPanelHeader.spec.js.snap, tests/unit/slidingPanel/slidingPanel.spec.js, tests/unit/slidingPanel/slidingPanelHeader.spec.js
* Added `slidingPanelHeader` component (for now internally, inside `slidingPanel`). 
* Added optional prop `title` to `slidingPanel` component. If it's defined we do show header.
* `slidingPanel` component is changed to support multiple close buttons.
* Diffs
* Added and adjusted to achieve 100% coverage
=> Add header to SlidingPanel component

components/googleMap/googleMap.md, styleguide.html
* Adds the public API Key for Google Maps to work to the styleguide's HTML. This key is restricted to specific domains, so cannot be used on non-travix domains ;-)
* Also removed the `apiKey` attribute on the `googleMap.md` since it's not used.
- Diffs
=> Adds public API Key for Google Maps to the styleguide's HTML

components/slidingPanel/slidingPanel.js, components/slidingPanel/slidingPanel.md, components/slidingPanel/slidingPanelHeader.js, tests/unit/slidingPanel/__snapshots__/slidingPanel.spec.js.snap, tests/unit/slidingPanel/__snapshots__/slidingPanelHeader.spec.js.snap, tests/unit/slidingPanel/slidingPanel.spec.js
* Changed `rel` attribute in close button to `data-rel` to be able to make custom close button with `<Button dataAttrs={({ rel: 'close' })} />` component.
* Diff
* Adapted to pass 100%
=> Change slidingPanel close button to use 'data-rel' attr instead of 'rel'

components/button/button.js, tests/unit/button/__snapshots__/button.spec.js.snap, tests/unit/button/button.spec.js
* Makes `onClick` prop of `Button` component is optional and resolves issue #72 
* Diff
* One test is removed and the snapshot is updated. Coverage is 100%.
=> Change Button's onClick prop to be optional

package.json
* Removes autoprefixer-loader and jest-serializer-enzyme which were not used anymore
- Diffs
=> Removes autoprefixer-loader and jest-serializer-enzyme from the package.json

package.json
* `react-select` package moved back to dependencies. Since we moved it out of it few errors have appeared (on tests and pipelines).
* Diff
* Passed
=> Move react-select from devDeps to deps

.travis.yml, package.json
* Due to a lack of maintenance from Coveralls side, we're switching to Codecov. For that I've enabled CodeCov integration with our repos + configured our .travis.yml to send the reports.
* Also added the codecov dependency to the repo.
Later on I'll remove the `coveralls` package, once it works properly
- `.travis.yml` and `package.json`
=> Changes our code coverage tool to use Code Cov

README.md, package.json, tests/jest.config.json
* Removes `coveralls` from the `devDependencies` on `package.json`.
* Removes the task `coverage:coveralls` on `package.json`
* Changes the _coverage_ badge to use the one from Codecov, rather than the one from Coveralls.
* Updates `tests/jest.config.json` to contain the property `rootDir` pointing to the project's root path. This fixes the coverage report which Jest was retrieving as `All files: Unknown`
- Check `package.json` and `README.md` changes
=> Removes coveralls dependency and changes the badge to connect to Codecov

.travis.yml
- Adds the flag `set -e` to the build process so that it stops the build as soon as it finds an error.
- Check the failing build being stopped at `ci:lint` task: https://travis-ci.org/Travix-International/travix-ui-kit/jobs/274109638
Since there's another issue with the CI process, it is expected that the build fails 😉
=> Adds 'set -e' to .travis.yml

.travis.yml, components/dropDown/dropDown.js, package.json, tests/jest.config.json, tests/unit/dropDown/__snapshots__/dropDown.render.spec.js.snap
- Due to changes in the releases > `v1.0.0-rc.5`, `react-select` broke the way we import it on the code. One way I found that worked was using their `dist/react-select.min.js` file. (I'm open for a proper, better solution if you have, but please try it locally).
- Diffs
- Build should pass now
(More info at: https://github.com/JedWatson/react-select/compare/v1.0.0-rc.5...v1.0.0-rc.7)
Closes #170
=> Fixes react-select's import

README.md
* Removes the remainders of the Coveralls badge
* Re-orders the badges so that NPM is first, then build and code coverage, and only after that it comes the integrations (Greenkeeper and Node Security Platform)
- If you look at our README.md on `master` you will notice that it contains remainders of the _coveralls_ badge on it, which needed to be removed. That's what this is fixing :)
=> Removes the remainders of the Coveralls badge and re-orders badges on README.md

components/tooltip/tooltip.scss
Increased z-index to prevent any overlapping.
components/tooltip/tooltip.scss
=> Tooltip fix: increased z-index to prevent overlapping

.gitignore, components/button/button.js, components/button/button.md, package.json
* Adds `classnames` as a package dependency
* Changes the `Button` component to support the `className` attribute. This is particularly important for CSS Modules since we need to pass a specific CSS Modules' class to style the element.
Also we don't want to follow the BEM style which the _mods_ attribute enforces.
* Also added an example with a custom class set.
- Diffs
- Check the styleguide :)
=> Add "className" prop to button

components/calendar/calendar.js, components/calendar/views/days.js
* Changes the `onSelectDay` method on `calendar.js` to use the `data-date` attribute from the `event's currentTarget` (which is provided from the `calendar/views/days.js` button.
- Diffs
=> Improves the calendar/views/days.js to not use .bind() according to react/jsx-no-bind lint rule

.travis.yml, Makefile, package.json
- Updates the `deploy:accp` script to prepend the generated now url with the git branch name.
- It additionally removes previous deployments under the same branch name in order to prevent you from hitting `now`'s limit on deployments.
- Run `npm run deploy:accp` and you should notice the generated url is in the format of `https://set-branch-name-on-deploy-accp-rnhcaoqrhp.now.sh/`
=> Updated deploy:accp script to prepend the generated now url with branch name

CHANGELOG.md, components/carousel/carousel.js, components/carousel/carousel.md, components/carousel/carouselTrack.js, tests/unit/carousel/__snapshots__/carousel.spec.js.snap, tests/unit/carousel/__snapshots__/carouselTrack.spec.js.snap, tests/unit/carousel/carouselTrack.spec.js
Added ability to use or not use touch events for track of carousel
Diff
=> Added ability to use or not use touch events for track of carousel

themes/_default.yaml
This PR fixes sliding panel overlay z-index, because of `feedback` button z-index (`fedback` button should not overlap sliding panel)
Look at diff
=> Fix sliding panel overlay z-index

components/autoComplete/autoComplete.scss, components/input/input.scss
* fixed `overflow-y` for autocomplete popunder (IE11 and Firefox)
* removed cross in input (IE11)
* diff
=> fixed css for autocomplete and input

styleguide.config.js
Fix error when running 'npm run styleguide-build' on Windows
Try to run 'npm run styleguide-build'
=> Fix styleguide.config.js for Windows

components/collapse/collapse.js, components/collapse/collapseItem.js, components/collapse/collapseItem.scss
* fixed styles for firefox and safari 9 for collapse and collapseItem components
* removed otherProps and added dataAttrs to collapse and collapseItem components
* added className prop to collapse and collapseItem components
* diff
=> Collapse fix

components/tooltip/tooltip.js, components/tooltip/tooltip.md, tests/unit/tooltip/__snapshots__/tooltip.render.spec.js.snap
- Adds the possibility to pass className and dataAttrs to the container of the tooltip component
- Removes dead prop
- unit test were updated
diffs in Tooltip.js,
=> added className and dataAttrs props and removed dead prop

components/loadingOverlay/loadingOverlay.js
This PR fixes the path to Spinner component from the LoadingOverlay component. It now follows the way it's done in other components. Cause: the issue with bundling in our core project (path cannot be resolved properly).
See the diff.
=> Fix the path to Spinner component from the LoadingOverlay component

components/modal/modal.js, components/modal/modal.scss, components/modal/modalContent.css, tests/unit/modal/__snapshots__/modal.render.spec.js.snap
- Fixes styles issue on IE 11
was:    
now:
- Fixes styles issue on safari 9/10
was:
now:
- Aligns height of content according to the design (small screen)
was: 
now:
=> fixed & improved styles for modal box (according to the design)

components/slidingPanel/slidingPanel.js
Needed different behavior for cases when user will click on the cross button and on submit button. For now, I'm not able to distinguish this clicks. Because clicking on any close button or changing component's props will trigger handleClose method and onTryingToClose callback and there are no differences between this calls.
One way, which I found, is to pass the event to handleClose in case of interacting with any DOM element. In case of props are changed arguments will be empty.
diffs
=> Improve handleClose method to use event

components/dropDown/dropDown.md, components/dropDown/dropDown.scss
This PR fixes issue with option height
Diff
=> Fix option height in dropdown with filter

package-lock.json, package.json, tests/unit/dropDown/__snapshots__/dropDown.render.spec.js.snap
- React select upgrade (getting rid of release candidate versions on our package.json)
- Changelog from react-select: https://github.com/JedWatson/react-select/blob/master/HISTORY.md
Breaking snapshots because of these new properties:
```js
<div>
<Select
-     addLabelText="Add "{label}"?"
arrowRenderer={[Function]}
autosize={true}
backspaceRemoves={true}
backspaceToRemoveMessage="Press backspace to remove {label}"
className="ui-dropdown"
@@ -35,15 +34,18 @@
openOnClick={true}
optionComponent={[Function]}
options={Array []}
pageSize={5}
placeholder=""
+     removeSelected={true}
required={false}
+     rtl={false}
scrollMenuIntoView={false}
searchable={true}
simpleValue={false}
tabSelectsValue={true}
+     trimFilter={true}
valueComponent={[Function]}
valueKey="value"
valueRenderer={null} …
```
=> Bump react-select to version 1.2.1
